// Geography the globe needs on top of the outline file in /assets/world-110m.json.

/** Where each demo program sits, as [lon, lat]. */
export const PROGRAM_COORDS: Record<string, [number, number]> = {
  valencia: [-0.38, 39.47],
  sapienza: [12.5, 41.9],
  bologna: [11.34, 44.49],
  porto: [-8.61, 41.15],
  lisbon: [-9.14, 38.72],
  eth: [8.54, 47.37],
};

/**
 * Russian names for the outline file's English ones. Every country the outline
 * file contains is listed, because any of them can be clicked; anything that
 * somehow is not falls back to the name in the data.
 */
export const COUNTRY_RU: Record<string, string> = {
  Afghanistan: "Афганистан",
  Angola: "Ангола",
  Antarctica: "Антарктида",
  Bangladesh: "Бангладеш",
  Benin: "Бенин",
  Bhutan: "Бутан",
  Bolivia: "Боливия",
  Botswana: "Ботсвана",
  "Burkina Faso": "Буркина-Фасо",
  Burundi: "Бурунди",
  Cambodia: "Камбоджа",
  Cameroon: "Камерун",
  "Central African Rep.": "ЦАР",
  Chad: "Чад",
  Colombia: "Колумбия",
  Congo: "Конго",
  "Costa Rica": "Коста-Рика",
  "Côte d'Ivoire": "Кот-д’Ивуар",
  Cuba: "Куба",
  "Dem. Rep. Congo": "ДР Конго",
  "Dominican Rep.": "Доминикана",
  Ecuador: "Эквадор",
  "Eq. Guinea": "Экваториальная Гвинея",
  Eritrea: "Эритрея",
  Ethiopia: "Эфиопия",
  "Falkland Is.": "Фолклендские острова",
  Fiji: "Фиджи",
  Gabon: "Габон",
  Ghana: "Гана",
  Greenland: "Гренландия",
  Guatemala: "Гватемала",
  Guinea: "Гвинея",
  "Guinea-Bissau": "Гвинея-Бисау",
  Guyana: "Гайана",
  Haiti: "Гаити",
  Honduras: "Гондурас",
  Jordan: "Иордания",
  Kenya: "Кения",
  Kyrgyzstan: "Киргизия",
  Laos: "Лаос",
  Lesotho: "Лесото",
  Liberia: "Либерия",
  Libya: "Ливия",
  Macedonia: "Северная Македония",
  Madagascar: "Мадагаскар",
  Malawi: "Малави",
  Malaysia: "Малайзия",
  Mali: "Мали",
  Mauritania: "Мавритания",
  Mongolia: "Монголия",
  Mozambique: "Мозамбик",
  Myanmar: "Мьянма",
  Namibia: "Намибия",
  Nepal: "Непал",
  Nicaragua: "Никарагуа",
  Niger: "Нигер",
  Nigeria: "Нигерия",
  "North Korea": "Северная Корея",
  Oman: "Оман",
  Pakistan: "Пакистан",
  Panama: "Панама",
  "Papua New Guinea": "Папуа — Новая Гвинея",
  Paraguay: "Парагвай",
  Peru: "Перу",
  Philippines: "Филиппины",
  "S. Sudan": "Южный Судан",
  Senegal: "Сенегал",
  "Sierra Leone": "Сьерра-Леоне",
  Somalia: "Сомали",
  Somaliland: "Сомалиленд",
  "Sri Lanka": "Шри-Ланка",
  Sudan: "Судан",
  Suriname: "Суринам",
  Syria: "Сирия",
  Taiwan: "Тайвань",
  Tajikistan: "Таджикистан",
  Tanzania: "Танзания",
  Thailand: "Таиланд",
  Togo: "Того",
  Tunisia: "Тунис",
  Turkmenistan: "Туркменистан",
  Uganda: "Уганда",
  Uruguay: "Уругвай",
  Uzbekistan: "Узбекистан",
  "W. Sahara": "Западная Сахара",
  Venezuela: "Венесуэла",
  Vietnam: "Вьетнам",
  Yemen: "Йемен",
  Zambia: "Замбия",
  Zimbabwe: "Зимбабве",
  Albania: "Албания",
  Algeria: "Алжир",
  Argentina: "Аргентина",
  Armenia: "Армения",
  Australia: "Австралия",
  Austria: "Австрия",
  Azerbaijan: "Азербайджан",
  Belarus: "Беларусь",
  Belgium: "Бельгия",
  "Bosnia and Herz.": "Босния и Герцеговина",
  Brazil: "Бразилия",
  Bulgaria: "Болгария",
  Canada: "Канада",
  Chile: "Чили",
  China: "Китай",
  Croatia: "Хорватия",
  Cyprus: "Кипр",
  Czechia: "Чехия",
  Denmark: "Дания",
  Egypt: "Египет",
  Estonia: "Эстония",
  Finland: "Финляндия",
  France: "Франция",
  Georgia: "Грузия",
  Germany: "Германия",
  Greece: "Греция",
  Hungary: "Венгрия",
  Iceland: "Исландия",
  India: "Индия",
  Indonesia: "Индонезия",
  Iran: "Иран",
  Iraq: "Ирак",
  Ireland: "Ирландия",
  Israel: "Израиль",
  Italy: "Италия",
  Japan: "Япония",
  Kazakhstan: "Казахстан",
  Kosovo: "Косово",
  Latvia: "Латвия",
  Lithuania: "Литва",
  Luxembourg: "Люксембург",
  Mexico: "Мексика",
  Moldova: "Молдова",
  Montenegro: "Черногория",
  Morocco: "Марокко",
  Netherlands: "Нидерланды",
  "New Zealand": "Новая Зеландия",
  "North Macedonia": "Северная Македония",
  Norway: "Норвегия",
  Poland: "Польша",
  Portugal: "Португалия",
  Romania: "Румыния",
  Russia: "Россия",
  "Saudi Arabia": "Саудовская Аравия",
  Serbia: "Сербия",
  Slovakia: "Словакия",
  Slovenia: "Словения",
  "South Africa": "ЮАР",
  "South Korea": "Южная Корея",
  Spain: "Испания",
  Sweden: "Швеция",
  Switzerland: "Швейцария",
  Turkey: "Турция",
  Ukraine: "Украина",
  "United Arab Emirates": "ОАЭ",
  "United Kingdom": "Великобритания",
  "United States of America": "США",
};

export const countryRu = (name: string) => COUNTRY_RU[name] ?? name;

/** Rough plain-language position, used when we have nothing else to say about a country. */
export function whereIs(lon: number, lat: number): string {
  const ns = lat >= 66 ? "за полярным кругом" : lat >= 35 ? "в северных широтах" : lat >= -23 ? "в тропиках" : "в южном полушарии";
  const ew = lon >= -25 && lon <= 45 ? "Европа и Африка" : lon > 45 && lon <= 150 ? "Азия" : lon > 150 || lon < -150 ? "Тихий океан" : "Америка";
  return `${ew}, ${ns}`;
}
