// ЕНТ, профильная математика: the demo knowledge model, its sets, what each topic is about and the
// checks that prove it. The plan in «Подготовке» is built for this exam (and SAT Math); IELTS is only
// a score the student tells us. Stands in for the backend, which will generate sets per student.
//
// Only types come from prepData: this file is imported by it, so it keeps its own date helper.

import type { Skill, StudySet, Task } from "./prepData";
import type { TopicContent } from "./topicContent";

const day = (month: number, date: number, year = 2026) => new Date(year, month - 1, date);

export const ENT_AREAS = ["Алгебра", "Функции и анализ", "Геометрия", "Вероятность"];

export const ENT_SKILLS: Omit<Skill, "exam">[] = [
  {
    id: "e-expr",
    name: "Выражения и дроби",
    area: "Алгебра",
    weight: 8,
    state: "solid",
    recall: 0.9,
    requires: [],
    misconceptions: [],
    evidence: [
      { source: "замер", text: "5 из 5 верно: дроби, проценты, формулы сокращённого умножения", date: day(9, 4) },
      { source: "мок", text: "Мок по сету 1: 6 из 6", date: day(9, 13) },
    ],
  },
  {
    id: "e-eq",
    name: "Уравнения и системы",
    area: "Алгебра",
    weight: 10,
    state: "solid",
    recall: 0.85,
    requires: ["e-expr"],
    misconceptions: [{ id: "eq-root", text: "Теряет отрицательный корень в x² = a", status: "resolved", observations: 2 }],
    evidence: [
      { source: "замер", text: "x² = 16: сначала только 4, потом исправил", date: day(9, 4) },
      { source: "мок", text: "Мок по сету 1: 5 из 6, ловушку с корнем обошёл", date: day(9, 13) },
    ],
  },
  {
    id: "e-func",
    name: "Функции и графики",
    area: "Функции и анализ",
    weight: 8,
    state: "solid",
    recall: 0.8,
    requires: ["e-eq"],
    misconceptions: [],
    evidence: [{ source: "мок", text: "Мок по сету 1: 5 из 6 — область определения и вершина параболы", date: day(9, 13) }],
  },
  {
    id: "e-roots",
    name: "Степени и корни",
    area: "Алгебра",
    weight: 7,
    state: "shaky",
    recall: 0.55,
    requires: ["e-expr"],
    misconceptions: [
      { id: "roots-mult", text: "Перемножает показатели вместо сложения при aᵐ · aⁿ", status: "suspected", observations: 1 },
    ],
    evidence: [{ source: "замер", text: "2³ · 2⁴: ответ 2¹² — ловушка «перемножил показатели»", date: day(9, 4) }],
  },
  {
    id: "e-log",
    name: "Логарифмы",
    area: "Функции и анализ",
    weight: 7,
    state: "weak",
    recall: 0.35,
    requires: ["e-roots"],
    root: true,
    misconceptions: [
      { id: "log-sum", text: "Складывает аргументы: lg a + lg b = lg(a + b)", status: "confirmed", observations: 2 },
    ],
    evidence: [
      { source: "замер", text: "lg 2 + lg 5: ответ lg 7 — ловушка «сложил аргументы»", date: day(9, 4) },
      { source: "чат", text: "«логарифм суммы — это сумма логарифмов, разве нет?»", date: day(9, 15) },
    ],
  },
  {
    id: "e-expeq",
    name: "Показательные и логарифмические уравнения",
    area: "Функции и анализ",
    weight: 8,
    state: "weak",
    recall: 0.3,
    requires: ["e-log", "e-eq"],
    misconceptions: [
      {
        id: "expeq-odz",
        text: "Не проверяет ОДЗ логарифма — оставляет посторонний корень",
        status: "confirmed",
        observations: 3,
        trigger: "когда у квадратного уравнения два «красивых» корня",
      },
    ],
    evidence: [
      { source: "замер", text: "lg x + lg(x − 3) = lg 4: ответ «4 и −1» — ловушка ОДЗ", date: day(9, 4) },
      { source: "задача", text: "log₂(x + 1) + log₂(x − 1) = 3: снова оставил отрицательный корень", date: day(9, 14) },
    ],
  },
  {
    id: "e-ineq",
    name: "Неравенства и метод интервалов",
    area: "Алгебра",
    weight: 9,
    state: "weak",
    recall: 0.4,
    requires: ["e-eq"],
    misconceptions: [
      { id: "ineq-zero", text: "Включает в ответ точку, где знаменатель равен нулю", status: "suspected", observations: 1 },
    ],
    evidence: [{ source: "замер", text: "(x − 2)/(x + 1) ≥ 0: включил x = −1", date: day(9, 4) }],
  },
  {
    id: "e-prog",
    name: "Прогрессии",
    area: "Алгебра",
    weight: 6,
    state: "lowData",
    recall: 0.45,
    requires: ["e-expr"],
    misconceptions: [],
    evidence: [],
  },
  {
    id: "e-trig",
    name: "Тригонометрия",
    area: "Функции и анализ",
    weight: 9,
    state: "shaky",
    recall: 0.5,
    requires: ["e-func"],
    misconceptions: [],
    evidence: [{ source: "замер", text: "2 из 3: sin x = 0 решил как x = 2πk", date: day(9, 4) }],
  },
  {
    id: "e-deriv",
    name: "Производная",
    area: "Функции и анализ",
    weight: 8,
    state: "shaky",
    recall: 0.55,
    requires: ["e-func"],
    misconceptions: [
      { id: "deriv-chain", text: "Забывает множитель внутренней функции", status: "suspected", observations: 1 },
    ],
    evidence: [{ source: "замер", text: "(sin 2x)′: ответ cos 2x", date: day(9, 4) }],
  },
  {
    id: "e-integral",
    name: "Первообразная и интеграл",
    area: "Функции и анализ",
    weight: 5,
    state: "lowData",
    recall: 0.4,
    requires: ["e-deriv"],
    misconceptions: [],
    evidence: [],
  },
  {
    id: "e-planim",
    name: "Планиметрия",
    area: "Геометрия",
    weight: 7,
    state: "shaky",
    recall: 0.6,
    requires: [],
    misconceptions: [],
    evidence: [{ source: "замер", text: "Трапеция: забыл разделить сумму оснований на 2", date: day(9, 4) }],
  },
  {
    id: "e-stereo",
    name: "Стереометрия",
    area: "Геометрия",
    weight: 5,
    state: "weak",
    recall: 0.35,
    requires: ["e-planim"],
    misconceptions: [],
    evidence: [{ source: "замер", text: "Объём конуса: забыл множитель 1/3", date: day(9, 4) }],
  },
  {
    id: "e-prob",
    name: "Вероятность и комбинаторика",
    area: "Вероятность",
    weight: 3,
    state: "lowData",
    recall: 0.45,
    requires: [],
    misconceptions: [],
    evidence: [],
  },
];

export const ENT_SETS: Omit<StudySet, "exam">[] = [
  {
    id: "e1",
    number: 1,
    title: "Выражения и уравнения",
    area: "Алгебра",
    skills: ["e-expr", "e-eq", "e-func"],
    start: day(9, 1),
    deadline: day(9, 14),
    status: "done",
    why: "Основа всего ЕНТ: без уверенных преобразований не решаются ни логарифмы, ни неравенства",
  },
  {
    id: "e2",
    number: 2,
    title: "Логарифмы и показательные уравнения",
    area: "Функции и анализ",
    skills: ["e-roots", "e-log", "e-expeq"],
    start: day(9, 15),
    deadline: day(10, 5),
    status: "upcoming",
    why: "Логарифмы — корень ошибок в уравнениях; ОДЗ — подтверждённая ловушка",
  },
  {
    id: "e3",
    number: 3,
    title: "Неравенства и прогрессии",
    area: "Алгебра",
    skills: ["e-ineq", "e-prog"],
    start: day(10, 6),
    deadline: day(10, 20),
    status: "upcoming",
    why: "Метод интервалов опирается на уравнения; по прогрессиям мало данных — короткая проверка",
  },
  {
    id: "e4",
    number: 4,
    title: "Производная и интеграл",
    area: "Функции и анализ",
    skills: ["e-deriv", "e-integral"],
    start: day(10, 21),
    deadline: day(11, 8),
    status: "upcoming",
    why: "Большой блок второй части ЕНТ; интеграл строится на производной",
  },
  {
    id: "e5",
    number: 5,
    title: "Тригонометрия и геометрия",
    area: "Геометрия",
    skills: ["e-trig", "e-planim", "e-stereo"],
    start: day(11, 9),
    deadline: day(12, 1),
    status: "upcoming",
    why: "Тригонометрия нужна для задач на треугольники; стереометрия опирается на планиметрию",
  },
  {
    id: "e6",
    number: 6,
    title: "Вероятность и комбинаторика",
    area: "Вероятность",
    skills: ["e-prob"],
    start: day(12, 2),
    deadline: day(12, 10),
    status: "upcoming",
    why: "Малый вес, но по теме мало данных — короткий сет",
  },
  {
    id: "e7",
    number: 7,
    title: "Закрепление перед ЕНТ",
    area: "Алгебра",
    skills: ["e-expeq", "e-ineq", "e-stereo"],
    start: day(12, 11),
    deadline: day(1, 15, 2027),
    status: "review",
    why: "Последний сет перед тестом — без новых тем, только ловушки и полный пробный ЕНТ",
  },
];

export const ENT_TOPICS: Record<string, TopicContent> = {
  "e-expr": {
    summary: "Преобразования: дроби, проценты, скобки и формулы сокращённого умножения. На ЕНТ это почти в каждой задаче, поэтому ошибка здесь тянет за собой остальные.",
    points: ["Приводить дроби к общему знаменателю", "Раскрывать (a ± b)² и a² − b²", "Считать проценты от числа"],
    example: { q: "(a² − b²) / (a − b) при a = 7, b = 3", a: "Сокращаем: a + b = 10" },
    trap: "Забыть удвоенное произведение: (x + 3)² ≠ x² + 9.",
  },
  "e-eq": {
    summary: "Линейные и квадратные уравнения и системы из двух уравнений. Квадратное решается через дискриминант или по теореме Виета.",
    points: ["Дискриминант D = b² − 4ac", "Теорема Виета: x₁ + x₂ = −b/a, x₁x₂ = c/a", "Подстановка и сложение в системах"],
    example: { q: "x² − 5x + 6 = 0", a: "По Виета: сумма 5, произведение 6 — корни 2 и 3" },
    trap: "В x² = 16 потерять корень −4.",
  },
  "e-func": {
    summary: "Как читать функцию по формуле и графику: область определения, пересечения с осями, вершина параболы, возрастание и убывание.",
    points: ["Знаменатель не равен нулю", "Вершина y = a(x − m)² + n — точка (m; n)", "Знак k решает, растёт ли прямая"],
    example: { q: "Вершина y = (x − 1)² + 4", a: "(1; 4)" },
    trap: "Взять знак из скобки: у (x − 1)² вершина в x = 1, а не −1.",
  },
  "e-roots": {
    summary: "Свойства степеней и корней: как умножать, делить и возводить степени, как выносить множитель из-под корня.",
    points: ["aᵐ · aⁿ = aᵐ⁺ⁿ, (aᵐ)ⁿ = aᵐⁿ", "a^(m/n) — корень n-й степени из aᵐ", "√(x²) = |x|"],
    example: { q: "8^(2/3)", a: "∛8 = 2, 2² = 4" },
    trap: "Перемножить показатели при умножении степеней: 2³ · 2⁴ ≠ 2¹².",
  },
  "e-log": {
    summary: "Логарифм — показатель степени: log_a b = c, если aᶜ = b. На ЕНТ нужны свойства: логарифм произведения, частного и степени.",
    points: ["log_a(bc) = log_a b + log_a c", "log_a(bᵏ) = k · log_a b", "a^(log_a b) = b"],
    example: { q: "lg 2 + lg 5", a: "lg(2 · 5) = lg 10 = 1" },
    trap: "Сложить аргументы: lg 2 + lg 5 ≠ lg 7.",
  },
  "e-expeq": {
    summary: "Уравнения, где x в показателе или под логарифмом. Приводим к одному основанию, решаем и обязательно проверяем ОДЗ.",
    points: ["Приводить к одному основанию", "Под логарифмом — только положительное", "Проверять каждый корень по ОДЗ"],
    example: { q: "lg x + lg(x − 3) = lg 4", a: "x(x − 3) = 4, корни 4 и −1; ОДЗ x > 3 — ответ 4" },
    trap: "Оставить корень, при котором логарифм не существует.",
  },
  "e-ineq": {
    summary: "Метод интервалов: отмечаем нули числителя и знаменателя, расставляем знаки и берём нужные промежутки.",
    points: ["При делении на отрицательное знак неравенства меняется", "Нули знаменателя всегда выколоты", "Проверять знак на каждом интервале"],
    example: { q: "(x − 1)(x − 4) < 0", a: "Между корнями: 1 < x < 4" },
    trap: "Включить в ответ точку, где знаменатель равен нулю.",
  },
  "e-prog": {
    summary: "Арифметическая прогрессия прибавляет d, геометрическая умножает на q. Нужны формулы n-го члена и суммы.",
    points: ["aₙ = a₁ + (n − 1)d", "bₙ = b₁ · qⁿ⁻¹", "Sₙ = (a₁ + aₙ) · n / 2"],
    example: { q: "a₁ = 3, d = 4. a₁₀?", a: "3 + 9 · 4 = 39" },
    trap: "Взять nd вместо (n − 1)d.",
  },
  "e-trig": {
    summary: "Значения синуса, косинуса и тангенса основных углов, основные тождества и простейшие уравнения.",
    points: ["sin²α + cos²α = 1", "Табличные значения 30°, 45°, 60°", "sin x = 0 при x = πk, cos x = 0 при x = π/2 + πk"],
    example: { q: "sin x = 0", a: "x = πk, k ∈ Z" },
    trap: "Записать x = 2πk и потерять половину решений.",
  },
  "e-deriv": {
    summary: "Производная показывает скорость изменения функции. На ЕНТ — таблица производных, сложная функция, касательная и экстремумы.",
    points: ["(xⁿ)′ = n · xⁿ⁻¹", "Сложная функция: умножить на производную внутренней", "Экстремум — там, где f′(x) = 0 и меняет знак"],
    example: { q: "(sin 2x)′", a: "cos 2x · 2 = 2cos 2x" },
    trap: "Забыть множитель внутренней функции.",
  },
  "e-integral": {
    summary: "Первообразная — обратное к производной. Определённый интеграл считает площадь под графиком по формуле Ньютона — Лейбница.",
    points: ["∫xⁿ dx = xⁿ⁺¹ / (n + 1) + C", "∫ₐᵇ f dx = F(b) − F(a)", "Площадь под графиком — интеграл"],
    example: { q: "∫₀¹ x dx", a: "x²/2 от 0 до 1 = 1/2" },
    trap: "Взять производную вместо первообразной.",
  },
  "e-planim": {
    summary: "Треугольники, четырёхугольники и окружность: площади, теорема Пифагора, углы.",
    points: ["Пифагор: c² = a² + b²", "S треугольника = ½ · a · h", "Вписанный угол — половина центрального"],
    example: { q: "Катеты 6 и 8", a: "Гипотенуза √(36 + 64) = 10" },
    trap: "Забыть ½ в площади треугольника или трапеции.",
  },
  "e-stereo": {
    summary: "Объёмы и площади поверхностей тел: куб, призма, цилиндр, конус, шар.",
    points: ["V конуса и пирамиды = ⅓ · S · h", "V шара = ⁴⁄₃ πr³", "Диагональ куба = a√3"],
    example: { q: "Конус r = 3, h = 4", a: "⅓ · π · 9 · 4 = 12π" },
    trap: "Забыть множитель ⅓ у конуса и пирамиды.",
  },
  "e-prob": {
    summary: "Классическая вероятность — благоприятные исходы на все. Комбинаторика считает, сколько этих исходов.",
    points: ["P = m / n", "Перестановки n!, сочетания C(n, k)", "Независимые события — вероятности перемножаются"],
    example: { q: "Две монеты: оба орла?", a: "½ · ½ = ¼" },
    trap: "Учесть порядок там, где он не важен.",
  },
};

const t = (id: string, text: string, options: Task["options"]): Task => ({ id, text, options });

export const ENT_CHECKS: Record<string, Task[]> = {
  "e-expr": [
    t("ee1", "(a² − b²) / (a − b) при a = 7, b = 3", [{ label: "10", correct: true }, { label: "4", trap: "Посчитал a − b вместо a + b" }, { label: "40" }, { label: "1" }]),
    t("ee2", "2/3 + 3/4 = ?", [{ label: "17/12", correct: true }, { label: "5/7", trap: "Сложил числители и знаменатели" }, { label: "6/12" }, { label: "1" }]),
    t("ee3", "0,2 · 0,3 = ?", [{ label: "0,06", correct: true }, { label: "0,6", trap: "Потерял разряд при умножении десятичных" }, { label: "0,5" }]),
    t("ee4", "(x + 3)² = ?", [{ label: "x² + 6x + 9", correct: true }, { label: "x² + 9", trap: "Забыл удвоенное произведение" }, { label: "x² + 3x + 9" }]),
    t("ee5", "15% от 240 = ?", [{ label: "36", correct: true }, { label: "24", trap: "Взял 10% вместо 15%" }, { label: "225" }, { label: "16" }]),
    t("ee6", "Сократите (x² − 4) / (x + 2)", [{ label: "x − 2", correct: true }, { label: "x + 2" }, { label: "x − 4", trap: "Сократил x² и x по отдельности" }]),
  ],
  "e-eq": [
    t("eq1", "2x − 5 = 9", [{ label: "x = 7", correct: true }, { label: "x = 2", trap: "Не сменил знак при переносе" }, { label: "x = 14" }]),
    t("eq2", "x² − 5x + 6 = 0", [{ label: "2 и 3", correct: true }, { label: "−2 и −3", trap: "Перепутал знаки корней по Виета" }, { label: "1 и 6" }]),
    t("eq3", "x + y = 5, x − y = 1. Решение (x; y)?", [{ label: "(3; 2)", correct: true }, { label: "(2; 3)", trap: "Перепутал x и y" }, { label: "(4; 1)" }]),
    t("eq4", "x² = 16", [{ label: "x = ±4", correct: true }, { label: "x = 4", trap: "Потерял отрицательный корень" }, { label: "x = 8" }]),
    t("eq5", "(x − 1)(x + 2) = 0", [{ label: "1 и −2", correct: true }, { label: "−1 и 2", trap: "Взял корни с противоположным знаком" }, { label: "1 и 2" }]),
    t("eq6", "Дискриминант x² + 2x + 5", [{ label: "−16", correct: true }, { label: "24", trap: "Прибавил 4ac вместо вычитания" }, { label: "16" }]),
  ],
  "e-func": [
    t("ef1", "y = 2x − 3 пересекает ось Oy в точке…", [{ label: "(0; −3)", correct: true }, { label: "(1,5; 0)", trap: "Нашёл пересечение с Ox" }, { label: "(0; 2)" }]),
    t("ef2", "Область определения y = 1 / (x − 2)", [{ label: "x ≠ 2", correct: true }, { label: "x > 2", trap: "Требует положительности вместо «не ноль»" }, { label: "все x" }]),
    t("ef3", "Вершина параболы y = (x − 1)² + 4", [{ label: "(1; 4)", correct: true }, { label: "(−1; 4)", trap: "Взял знак из скобки" }, { label: "(1; −4)" }]),
    t("ef4", "Куда направлены ветви y = −x² + 3?", [{ label: "Вниз", correct: true }, { label: "Вверх", trap: "Не учёл минус перед x²" }]),
    t("ef5", "f(x) = x² + 1. f(−2) = ?", [{ label: "5", correct: true }, { label: "−3", trap: "Посчитал −2² как −4" }, { label: "3" }]),
    t("ef6", "Убывает ли y = −3x + 1?", [{ label: "Да, коэффициент при x отрицательный", correct: true }, { label: "Нет, ведь +1", trap: "Смотрит на свободный член вместо k" }]),
  ],
  "e-roots": [
    t("er1", "2³ · 2⁴ = ?", [{ label: "2⁷", correct: true }, { label: "2¹²", trap: "Перемножил показатели вместо сложения" }, { label: "4⁷" }]),
    t("er2", "√50 = ?", [{ label: "5√2", correct: true }, { label: "25√2", trap: "Вынес 25, а не его корень" }, { label: "10√5" }]),
    t("er3", "8^(2/3) = ?", [{ label: "4", correct: true }, { label: "16/3", trap: "Умножил основание на показатель" }, { label: "2" }]),
    t("er4", "−3² = ?", [{ label: "−9", correct: true }, { label: "9", trap: "Возвёл минус в квадрат вместе с числом" }, { label: "−6" }]),
    t("er5", "5⁰ = ?", [{ label: "1", correct: true }, { label: "0", trap: "Считает, что нулевая степень даёт ноль" }, { label: "5" }]),
    t("er6", "√(x²) при x = −4", [{ label: "4", correct: true }, { label: "−4", trap: "√(x²) = x — забыл про модуль" }, { label: "16" }]),
  ],
  "e-log": [
    t("el1", "log₂ 8 = ?", [{ label: "3", correct: true }, { label: "4", trap: "Разделил 8 на 2" }, { label: "16" }]),
    t("el2", "log₃ 1 = ?", [{ label: "0", correct: true }, { label: "1", trap: "Считает, что логарифм единицы — 1" }, { label: "3" }]),
    t("el3", "lg 2 + lg 5 = ?", [{ label: "1", correct: true }, { label: "lg 7", trap: "Сложил аргументы вместо умножения" }, { label: "10" }]),
    t("el4", "log₂ 32 − log₂ 4 = ?", [{ label: "3", correct: true }, { label: "log₂ 28", trap: "Вычел аргументы вместо деления" }, { label: "8" }]),
    t("el5", "2^(log₂ 7) = ?", [{ label: "7", correct: true }, { label: "14", trap: "Умножил основание на аргумент" }, { label: "2⁷" }]),
    t("el6", "log₅ 625 = ?", [{ label: "4", correct: true }, { label: "125", trap: "Разделил аргумент на основание" }, { label: "5" }]),
  ],
  "e-expeq": [
    t("ex1", "2ˣ = 16", [{ label: "x = 4", correct: true }, { label: "x = 8", trap: "Разделил 16 на 2" }, { label: "x = 3" }]),
    t("ex2", "log₂(x − 1) = 3", [{ label: "x = 9", correct: true }, { label: "x = 7", trap: "Умножил 2 на 3 вместо возведения в степень" }, { label: "x = 4" }]),
    t("ex3", "lg x + lg(x − 3) = lg 4", [{ label: "4", correct: true }, { label: "4 и −1", trap: "Не проверил ОДЗ логарифма" }, { label: "−1" }]),
    t("ex4", "3^(x + 1) = 27", [{ label: "x = 2", correct: true }, { label: "x = 3", trap: "Забыл про +1 в показателе" }, { label: "x = 26" }]),
    t("ex5", "4ˣ = 2^(x + 3)", [{ label: "x = 3", correct: true }, { label: "x = 1", trap: "Не привёл к одному основанию" }, { label: "x = 3/2" }]),
    t("ex6", "log₂ x = −1", [{ label: "x = 1/2", correct: true }, { label: "x = −2", trap: "Умножил основание на показатель" }, { label: "Нет решений", trap: "Считает, что логарифм не бывает отрицательным" }]),
  ],
  "e-ineq": [
    t("ei1", "−2x > 6", [{ label: "x < −3", correct: true }, { label: "x > −3", trap: "Не перевернул знак при делении на отрицательное" }, { label: "x < 3" }]),
    t("ei2", "(x − 1)(x − 4) < 0", [{ label: "1 < x < 4", correct: true }, { label: "x < 1 или x > 4", trap: "Перепутал знаки интервалов" }, { label: "x > 4" }]),
    t("ei3", "x² ≤ 9", [{ label: "−3 ≤ x ≤ 3", correct: true }, { label: "x ≤ 3", trap: "Потерял левую границу" }, { label: "x ≥ 3" }]),
    t("ei4", "(x − 2) / (x + 1) ≥ 0", [{ label: "x < −1 или x ≥ 2", correct: true }, { label: "x ≤ −1 или x ≥ 2", trap: "Включил точку, где знаменатель равен нулю" }, { label: "−1 < x ≤ 2" }]),
    t("ei5", "Сколько целых x удовлетворяют −2 < x ≤ 3?", [{ label: "5", correct: true }, { label: "6", trap: "Включил строгую границу −2" }, { label: "4" }]),
    t("ei6", "|x| < 5", [{ label: "−5 < x < 5", correct: true }, { label: "x < 5", trap: "Потерял вторую ветвь модуля" }, { label: "x > −5" }]),
  ],
  "e-prog": [
    t("ep1", "a₁ = 3, d = 4. a₁₀ = ?", [{ label: "39", correct: true }, { label: "43", trap: "Взял 10d вместо 9d" }, { label: "40" }]),
    t("ep2", "b₁ = 2, q = 3. b₄ = ?", [{ label: "54", correct: true }, { label: "162", trap: "Взял q⁴ вместо q³" }, { label: "24" }]),
    t("ep3", "1 + 2 + … + 100 = ?", [{ label: "5050", correct: true }, { label: "10100", trap: "Не разделил на 2" }, { label: "5000" }]),
    t("ep4", "5, 8, 11, … Разность прогрессии?", [{ label: "3", correct: true }, { label: "8/5", trap: "Разделил члены вместо вычитания" }, { label: "5" }]),
    t("ep5", "a₁ = 2, d = 2. Сумма первых пяти членов?", [{ label: "30", correct: true }, { label: "60", trap: "Не разделил на 2" }, { label: "20" }]),
    t("ep6", "b₁ = 6, q = 1/2. Сумма бесконечно убывающей прогрессии?", [{ label: "12", correct: true }, { label: "3", trap: "Умножил на q вместо деления на 1 − q" }, { label: "6" }]),
  ],
  "e-trig": [
    t("et1", "sin 30° = ?", [{ label: "1/2", correct: true }, { label: "√3/2", trap: "Перепутал sin и cos 30°" }, { label: "1" }]),
    t("et2", "cos 60° = ?", [{ label: "1/2", correct: true }, { label: "√3/2", trap: "Перепутал sin и cos 60°" }, { label: "0" }]),
    t("et3", "sin²α + cos²α = ?", [{ label: "1", correct: true }, { label: "sin 2α", trap: "Спутал с формулой двойного угла" }, { label: "0" }]),
    t("et4", "tg 45° = ?", [{ label: "1", correct: true }, { label: "√3", trap: "Перепутал с tg 60°" }, { label: "0" }]),
    t("et5", "sin x = 0", [{ label: "x = πk", correct: true }, { label: "x = 2πk", trap: "Потерял половину решений" }, { label: "x = π/2 + πk", trap: "Перепутал с cos x = 0" }]),
    t("et6", "180° в радианах", [{ label: "π", correct: true }, { label: "2π", trap: "Взял полный оборот" }, { label: "π/2" }]),
  ],
  "e-deriv": [
    t("ed1", "(x³)′ = ?", [{ label: "3x²", correct: true }, { label: "x²", trap: "Не умножил на показатель" }, { label: "3x³" }]),
    t("ed2", "(5x − 2)′ = ?", [{ label: "5", correct: true }, { label: "5x", trap: "Оставил x после дифференцирования" }, { label: "3" }]),
    t("ed3", "(sin 2x)′ = ?", [{ label: "2cos 2x", correct: true }, { label: "cos 2x", trap: "Забыл множитель внутренней функции" }, { label: "−2cos 2x" }]),
    t("ed4", "f(x) = x². f′(3) = ?", [{ label: "6", correct: true }, { label: "9", trap: "Подставил в функцию, а не в производную" }, { label: "3" }]),
    t("ed5", "Точка экстремума y = x² − 4x", [{ label: "x = 2", correct: true }, { label: "x = 4", trap: "Нашёл корень функции, а не производной" }, { label: "x = 0" }]),
    t("ed6", "(eˣ)′ = ?", [{ label: "eˣ", correct: true }, { label: "x · eˣ⁻¹", trap: "Применил правило степени к показательной функции" }, { label: "1" }]),
  ],
  "e-integral": [
    t("eg1", "Первообразная для 2x", [{ label: "x² + C", correct: true }, { label: "2 + C", trap: "Взял производную вместо первообразной" }, { label: "2x² + C" }]),
    t("eg2", "∫₀¹ x dx = ?", [{ label: "1/2", correct: true }, { label: "1", trap: "Забыл разделить на 2" }, { label: "0" }]),
    t("eg3", "Первообразная для cos x", [{ label: "sin x + C", correct: true }, { label: "−sin x + C", trap: "Перепутал знак" }, { label: "−cos x + C" }]),
    t("eg4", "∫₀² 3 dx = ?", [{ label: "6", correct: true }, { label: "3", trap: "Не умножил на длину отрезка" }, { label: "0" }]),
    t("eg5", "Первообразная для x³", [{ label: "x⁴/4 + C", correct: true }, { label: "3x² + C", trap: "Взял производную вместо первообразной" }, { label: "x⁴ + C" }]),
    t("eg6", "Площадь под y = x² на [0; 3]", [{ label: "9", correct: true }, { label: "27", trap: "Не разделил на 3" }, { label: "3" }]),
  ],
  "e-planim": [
    t("pl1", "Сумма углов треугольника", [{ label: "180°", correct: true }, { label: "360°", trap: "Перепутал с четырёхугольником" }, { label: "90°" }]),
    t("pl2", "Катеты 6 и 8. Гипотенуза?", [{ label: "10", correct: true }, { label: "14", trap: "Сложил катеты" }, { label: "48" }]),
    t("pl3", "Площадь круга радиуса 3", [{ label: "9π", correct: true }, { label: "6π", trap: "Посчитал длину окружности" }, { label: "3π" }]),
    t("pl4", "Вписанный угол опирается на дугу 100°. Чему он равен?", [{ label: "50°", correct: true }, { label: "100°", trap: "Взял центральный угол" }, { label: "200°" }]),
    t("pl5", "Треугольник: основание 10, высота 6. Площадь?", [{ label: "30", correct: true }, { label: "60", trap: "Забыл множитель ½" }, { label: "16" }]),
    t("pl6", "Трапеция: основания 4 и 10, высота 5. Площадь?", [{ label: "35", correct: true }, { label: "70", trap: "Не разделил сумму оснований на 2" }, { label: "19" }]),
  ],
  "e-stereo": [
    t("st1", "Объём куба с ребром 3", [{ label: "27", correct: true }, { label: "9", trap: "Посчитал площадь грани" }, { label: "54" }]),
    t("st2", "Объём цилиндра: r = 2, h = 5", [{ label: "20π", correct: true }, { label: "10π", trap: "Взял r вместо r²" }, { label: "40π" }]),
    t("st3", "Объём конуса: r = 3, h = 4", [{ label: "12π", correct: true }, { label: "36π", trap: "Забыл множитель ⅓" }, { label: "24π" }]),
    t("st4", "Объём шара радиуса 3", [{ label: "36π", correct: true }, { label: "27π", trap: "Забыл множитель ⁴⁄₃" }, { label: "12π" }]),
    t("st5", "Площадь полной поверхности куба с ребром 2", [{ label: "24", correct: true }, { label: "8", trap: "Посчитал объём" }, { label: "16" }]),
    t("st6", "Диагональ куба с ребром a", [{ label: "a√3", correct: true }, { label: "a√2", trap: "Взял диагональ грани" }, { label: "3a" }]),
  ],
  "e-prob": [
    t("pr1", "Вероятность чётного числа на кубике", [{ label: "1/2", correct: true }, { label: "1/3", trap: "Посчитал только 2 и 4" }, { label: "1/6" }]),
    t("pr2", "5! = ?", [{ label: "120", correct: true }, { label: "15", trap: "Сложил вместо умножения" }, { label: "25" }]),
    t("pr3", "Сколькими способами выбрать 2 человек из 5?", [{ label: "10", correct: true }, { label: "20", trap: "Учёл порядок, где он не важен" }, { label: "25" }]),
    t("pr4", "Две монеты. Вероятность двух орлов?", [{ label: "1/4", correct: true }, { label: "1/2", trap: "Не перемножил вероятности независимых событий" }, { label: "1/3" }]),
    t("pr5", "3 белых и 7 чёрных шаров. Вероятность вынуть белый?", [{ label: "3/10", correct: true }, { label: "3/7", trap: "Разделил на число чёрных, а не всех" }, { label: "7/10" }]),
    t("pr6", "Сколько трёхзначных чисел из цифр 1, 2, 3 без повторов?", [{ label: "6", correct: true }, { label: "27", trap: "Разрешил повторы цифр" }, { label: "9" }]),
  ],
};
