/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_profile_patch"];
        trace?: never;
    };
    "/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved */
        get: operations["list_saved_saved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Program */
        post: operations["save_program_saved__program_id__post"];
        /** Remove Saved */
        delete: operations["remove_saved_saved__program_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["list_programs_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program */
        get: operations["get_program_programs__program_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{kind}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_chat__kind__messages_get"];
        put?: never;
        /** Post Message */
        post: operations["post_message_chat__kind__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prep/knowledge/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Version */
        get: operations["get_knowledge_version_prep_knowledge_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Task */
        post: operations["issue_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{instance_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Task */
        post: operations["answer_task_tasks__instance_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{instance_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip Task */
        post: operations["skip_task_tasks__instance_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{instance_id}/solution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solution */
        get: operations["get_solution_tasks__instance_id__solution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sets */
        get: operations["list_sets_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Set */
        post: operations["switch_set_sets_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Set */
        get: operations["get_set_sets__set_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Set */
        patch: operations["edit_set_sets__set_id__patch"];
        trace?: never;
    };
    "/sets/{set_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Set */
        post: operations["open_set_sets__set_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}/topics/{skill_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Topic */
        post: operations["open_topic_sets__set_id__topics__skill_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}/topics/{skill_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Topic */
        post: operations["complete_topic_sets__set_id__topics__skill_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge */
        get: operations["get_knowledge_knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/explain/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain */
        get: operations["explain_knowledge_explain__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/misconceptions/{misconception_id}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispute */
        post: operations["dispute_knowledge_misconceptions__misconception_id__dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Matching */
        get: operations["get_matching_matching_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matching/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Matching */
        get: operations["compare_matching_matching_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview/milestones/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Milestone */
        post: operations["mark_milestone_overview_milestones__key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Diagnostic */
        post: operations["start_diagnostic_diagnostic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostic/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Diagnostic */
        get: operations["active_diagnostic_diagnostic_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostic/{run_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Diagnostic */
        post: operations["answer_diagnostic_diagnostic__run_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostic/{run_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Diagnostic */
        post: operations["finish_diagnostic_diagnostic__run_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Mock */
        post: operations["start_mock_mocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mock */
        get: operations["get_mock_mocks__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{run_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Mock */
        post: operations["answer_mock_mocks__run_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{run_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Mock */
        post: operations["finish_mock_mocks__run_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Academics */
        Academics: {
            self_assessment?: components["schemas"]["ProfileField_dict_str__int__"];
            ent_trial_score?: components["schemas"]["ProfileField_int_"];
            ent_profile_pair?: components["schemas"]["ProfileField_list_str__"];
            sat_score?: components["schemas"]["ProfileField_int_"];
            sat_target?: components["schemas"]["ProfileField_int_"];
            sat_date?: components["schemas"]["ProfileField_date_"];
            ielts_score?: components["schemas"]["ProfileField_float_"];
            ielts_target?: components["schemas"]["ProfileField_float_"];
        };
        /** AnswerIn */
        AnswerIn: {
            /**
             * Instance Id
             * Format: uuid
             */
            instance_id: string;
            /** Answer */
            answer: unknown;
            /** Time Spent Sec */
            time_spent_sec: number;
            /** Mode */
            mode: string;
            /**
             * After Guideline
             * @default false
             */
            after_guideline: boolean;
            /**
             * Hint Level Before
             * @default 0
             */
            hint_level_before: number;
        };
        /** AnswerResult */
        AnswerResult: {
            grade: components["schemas"]["Grade"];
            /** Solution */
            solution: string[];
            /** State After */
            state_after?: unknown;
            misconception_change?: components["schemas"]["MisconceptionChange"] | null;
            /** State Words */
            state_words: string;
            /** Knowledge Version */
            knowledge_version: number;
        };
        /** AssistantMarkup */
        AssistantMarkup: {
            /** Mode */
            mode?: string | null;
            /** Gave Task Instance Id */
            gave_task_instance_id?: string | null;
            /** Hint Level */
            hint_level?: number | null;
            /** Referenced Skill Ids */
            referenced_skill_ids?: string[];
        };
        /** ChatMessageIn */
        ChatMessageIn: {
            /** Text */
            text: string;
            /** Topic Skill Id */
            topic_skill_id?: string | null;
            /** Set Id */
            set_id?: string | null;
        };
        /** CompareOut */
        CompareOut: {
            /** Program Ids */
            program_ids: string[];
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
            /** Collapsed Same */
            collapsed_same: string[];
            /** Conclusion */
            conclusion: string | null;
        };
        /** CompareRow */
        CompareRow: {
            /** Param */
            param: string;
            /** Values */
            values: {
                [key: string]: string;
            };
            /** Differs */
            differs: boolean;
            /** Relevant To Student */
            relevant_to_student: boolean;
            source: components["schemas"]["Source"] | null;
        };
        /** ConflictOut */
        ConflictOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "same_day_applications" | "exclusive_rounds" | "exam_after_deadline";
            /** Milestone Keys */
            milestone_keys: string[];
            /** Text */
            text: string;
            /** Options */
            options: string[];
        };
        /** Constraints */
        Constraints: {
            required?: components["schemas"]["ProfileField_list_str__"];
            excluded?: components["schemas"]["ProfileField_list_str__"];
        };
        /** Deadline */
        Deadline: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "application" | "scholarship" | "exam_registration" | "other";
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Round */
            round?: string | null;
            /** Source */
            source: string;
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
            /** Is Demo */
            is_demo: boolean;
        };
        /** DiagnosticOut */
        DiagnosticOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "abandoned";
            state: components["schemas"]["DiagnosticState"];
            next_task: components["schemas"]["TaskInstanceOut"] | null;
        };
        /** DiagnosticResult */
        DiagnosticResult: {
            /** Firm */
            firm: string[];
            /** Shaky */
            shaky: string[];
            /** Roots */
            roots: components["schemas"]["RootCauseOut"][];
            /** Suspected */
            suspected: string[];
            /** Start From */
            start_from: string[];
            /** Words */
            words: string;
        };
        /** DiagnosticStartIn */
        DiagnosticStartIn: {
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** N Tasks */
            n_tasks: number | null;
        };
        /** DiagnosticState */
        DiagnosticState: {
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Budget Left */
            budget_left: number;
            /** Reserve Left */
            reserve_left: number;
            /** Asked */
            asked: string[];
            /** Answered */
            answered: number;
            /** Pending Descent */
            pending_descent: string[];
            /** Reask Queue */
            reask_queue: [
                string,
                number
            ][];
            /** Roots Found */
            roots_found: components["schemas"]["RootCauseOut"][];
            /** Trap Hits */
            trap_hits: string[];
            /** Firm */
            firm: string[];
            /** Shaky */
            shaky: string[];
            /** Last Grade Correct */
            last_grade_correct: boolean | null;
        };
        /** Direction */
        Direction: {
            field?: components["schemas"]["ProfileField_str_"];
            alternatives?: components["schemas"]["ProfileField_list_str__"];
        };
        /** DisputeIn */
        DisputeIn: {
            /** Disputed */
            disputed: boolean;
        };
        /** EvidenceListOut */
        EvidenceListOut: {
            /** Items */
            items: components["schemas"]["EvidenceOut"][];
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Evidence Id */
            evidence_id: string;
            /** Event Id */
            event_id: number;
            /** Skill Id */
            skill_id: string;
            /** Kind */
            kind: string;
            /**
             * Tier
             * @enum {integer}
             */
            tier: 1 | 2 | 3;
            /**
             * Source
             * @enum {string}
             */
            source: "task" | "mock" | "diagnostic" | "chat" | "self_report";
            /** Weight */
            weight: number;
            /**
             * Direction
             * @enum {integer}
             */
            direction: 1 | -1 | 0;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Summary */
            summary: string | null;
            /** Instance Id */
            instance_id: string | null;
            /** Message Id */
            message_id: string | null;
        };
        /** ExamProgress */
        ExamProgress: {
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Readiness */
            readiness: number;
            forecast: components["schemas"]["ForecastOut"] | null;
            /** Milestones Done */
            milestones_done: number;
            /** Milestones Total */
            milestones_total: number;
        };
        /** ExamRequirementOut */
        ExamRequirementOut: {
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Target Score */
            target_score: number;
            /**
             * Target Source
             * @enum {string}
             */
            target_source: "programs" | "manual";
            /** Max Raw Score */
            max_raw_score: number;
            /** Program Ids */
            program_ids: string[];
            /** Test Dates */
            test_dates: components["schemas"]["TestDate"][];
            /** Has Knowledge Model */
            has_knowledge_model: boolean;
            /** Current Estimate */
            current_estimate: number | null;
            /** Estimate Note */
            estimate_note: string;
        };
        /** FactorOut */
        FactorOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "hard" | "soft";
            /**
             * Status
             * @enum {string}
             */
            status: "below" | "in_range" | "above" | "unknown";
            /** Text */
            text: string;
            source: components["schemas"]["Source"] | null;
            /** Weight */
            weight: number;
        };
        /** ForecastOut */
        ForecastOut: {
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Predicted Raw */
            predicted_raw: number;
            /** Predicted Scaled */
            predicted_scaled: number | null;
            /** Coverage */
            coverage: number;
            /** Hours Needed */
            hours_needed: number;
            /** Ready By */
            ready_by: string | null;
            /** Test Date */
            test_date: string | null;
            /** On Track */
            on_track: boolean | null;
            /** As Of Event Id */
            as_of_event_id: number;
            /** Note */
            note: string;
        };
        /** Grade */
        Grade: {
            /** Correct */
            correct: boolean;
            /** Matched Misconception Id */
            matched_misconception_id?: string | null;
            /** Partial */
            partial?: number | null;
            /**
             * Omitted Misconception Ids
             * @default []
             */
            omitted_misconception_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checks */
            checks: {
                [key: string]: ("ok" | "down" | "skipped") | number;
            };
            /**
             * Llm Status
             * @enum {string}
             */
            llm_status: "ok" | "degraded" | "down";
            /** Version */
            version: string;
        };
        /** KnowledgeOut */
        KnowledgeOut: {
            /** Skills */
            skills: components["schemas"]["SkillStateView"][];
            /** Misconceptions */
            misconceptions: components["schemas"]["MisconceptionStateOut"][];
            /** Roots */
            roots: components["schemas"]["RootCauseOut"][];
        };
        /** KnowledgeVersionOut */
        KnowledgeVersionOut: {
            /** Version */
            version: number;
        };
        /** Level */
        Level: {
            grade?: components["schemas"]["ProfileField_int_"];
            admission_year?: components["schemas"]["ProfileField_int_"];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MatchOut */
        MatchOut: {
            program: components["schemas"]["Program"];
            /**
             * Realism
             * @enum {string}
             */
            realism: "impossible" | "try" | "possible";
            /** Factors */
            factors: components["schemas"]["FactorOut"][];
            /** Assumptions */
            assumptions: string[];
            /** Score */
            score: number;
            /** Fits Text */
            fits_text: string | null;
            /** Soft Pending */
            soft_pending: boolean;
        };
        /** MatchingOut */
        MatchingOut: {
            /** Items */
            items: components["schemas"]["MatchOut"][];
            /** Total */
            total: number;
            /** Profile Readiness */
            profile_readiness: number;
            /** Forecast Used */
            forecast_used: boolean;
            /** Empty Reason */
            empty_reason: string | null;
        };
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Text */
            text: string;
            markup?: components["schemas"]["AssistantMarkup"] | null;
            /** Event Id */
            event_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MilestoneMarkIn */
        MilestoneMarkIn: {
            /** Done */
            done: boolean;
        };
        /** MilestoneOut */
        MilestoneOut: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "registration" | "test" | "application" | "document" | "scholarship" | "window";
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Title */
            title: string;
            /** Exam Id */
            exam_id: ("SAT_MATH" | "ENT_MATH") | null;
            /** Program Id */
            program_id: string | null;
            source: components["schemas"]["Source"];
            /** Done */
            done: boolean;
            /** Done At */
            done_at?: string | null;
        };
        /** MisconceptionChange */
        MisconceptionChange: {
            /** Misconception Id */
            misconception_id: string;
            /** From Status */
            from_status: ("suspected" | "confirmed" | "resolved" | "disputed") | null;
            /**
             * To Status
             * @enum {string}
             */
            to_status: "suspected" | "confirmed" | "resolved" | "disputed";
            /** Counters */
            counters: {
                [key: string]: unknown;
            };
        };
        /**
         * MisconceptionStateOut
         * @description State of one misconception for one student — memory-architecture §5.
         */
        MisconceptionStateOut: {
            /** Misconception Id */
            misconception_id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "suspected" | "confirmed" | "resolved" | "disputed";
            /** Occurrence Count */
            occurrence_count: number;
            /** Strong Count */
            strong_count: number;
            /** Consecutive Avoided */
            consecutive_avoided: number;
            /** Triggers */
            triggers: {
                [key: string]: unknown;
            };
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Skill Ids */
            skill_ids: string[];
            /**
             * Visible Label
             * @default
             */
            visible_label: string;
        };
        /** MockOut */
        MockOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "mock_set" | "mock_topic" | "mock_misconception";
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Section Name */
            section_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "abandoned";
            /** Tasks */
            tasks: components["schemas"]["TaskInstanceOut"][];
            /** Minutes */
            minutes: number;
            /** Answered */
            answered: number;
            /** Predicted Before */
            predicted_before: number | null;
        };
        /** MockResultOut */
        MockResultOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Raw Score */
            raw_score: number;
            /** Max Raw */
            max_raw: number;
            /** Scaled Score */
            scaled_score: number | null;
            /** Scale Note */
            scale_note: string | null;
            /** Per Skill */
            per_skill: components["schemas"]["SkillStateView"][];
            /** Brier Point */
            brier_point: number | null;
        };
        /** MockStartIn */
        MockStartIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "mock_set" | "mock_topic" | "mock_misconception";
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Set Id */
            set_id: string | null;
            /** Skill Id */
            skill_id: string | null;
            /** Misconception Id */
            misconception_id: string | null;
        };
        /** OptionOut */
        OptionOut: {
            /** Key */
            key: string;
            /** Text */
            text: string;
        };
        /** OverviewOut */
        OverviewOut: {
            /** Requirements */
            requirements: components["schemas"]["ExamRequirementOut"][];
            /** Milestones */
            milestones: components["schemas"]["MilestoneOut"][];
            /** Conflicts */
            conflicts: components["schemas"]["ConflictOut"][];
            /** Progress */
            progress: components["schemas"]["ExamProgress"][];
            last_set_summary: components["schemas"]["SetSummaryOut"] | null;
        };
        /** Pace */
        Pace: {
            hours_per_week?: components["schemas"]["ProfileField_int_"];
            explanation_depth?: components["schemas"]["ProfileField_Literal__short____normal____deep___"];
            hint_level?: components["schemas"]["ProfileField_Literal__minimal____normal____generous___"];
        };
        /** Page[Program] */
        Page_Program_: {
            /** Items */
            items: components["schemas"]["Program"][];
            /** Total */
            total: number;
        };
        /** Page[SavedProgramWithProgram] */
        Page_SavedProgramWithProgram_: {
            /** Items */
            items: components["schemas"]["SavedProgramWithProgram"][];
            /** Total */
            total: number;
        };
        /** Preferences */
        Preferences: {
            countries?: components["schemas"]["ProfileField_list_str__"];
            cities?: components["schemas"]["ProfileField_list_str__"];
            language?: components["schemas"]["ProfileField_str_"];
            budget_per_year?: components["schemas"]["ProfileField_int_"];
            currency?: components["schemas"]["ProfileField_str_"];
            grant_need?: components["schemas"]["ProfileField_Literal__only_grant____preferred____not_needed___"];
        };
        /** Priorities */
        Priorities: {
            ranking?: components["schemas"]["ProfileField_list_Literal__realism____cost____ranking____location____program____research____mobility____"];
        };
        /** Profile */
        Profile: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            questionnaire?: components["schemas"]["Questionnaire"];
            traits?: components["schemas"]["Traits"];
            /**
             * Readiness
             * @default 0
             */
            readiness: number;
        };
        /** ProfileField[Literal['minimal', 'normal', 'generous']] */
        ProfileField_Literal__minimal____normal____generous___: {
            /** Value */
            value?: ("minimal" | "normal" | "generous") | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[Literal['only_grant', 'preferred', 'not_needed']] */
        ProfileField_Literal__only_grant____preferred____not_needed___: {
            /** Value */
            value?: ("only_grant" | "preferred" | "not_needed") | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[Literal['short', 'normal', 'deep']] */
        ProfileField_Literal__short____normal____deep___: {
            /** Value */
            value?: ("short" | "normal" | "deep") | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[date] */
        ProfileField_date_: {
            /** Value */
            value?: string | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[dict[str, int]] */
        ProfileField_dict_str__int__: {
            /** Value */
            value?: {
                [key: string]: number;
            } | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[float] */
        ProfileField_float_: {
            /** Value */
            value?: number | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[int] */
        ProfileField_int_: {
            /** Value */
            value?: number | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[list[Literal['realism', 'cost', 'ranking', 'location', 'program', 'research', 'mobility']]] */
        ProfileField_list_Literal__realism____cost____ranking____location____program____research____mobility____: {
            /** Value */
            value?: ("realism" | "cost" | "ranking" | "location" | "program" | "research" | "mobility")[] | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[list[str]] */
        ProfileField_list_str__: {
            /** Value */
            value?: string[] | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileField[str] */
        ProfileField_str_: {
            /** Value */
            value?: string | null;
            /**
             * Mark
             * @default default
             * @enum {string}
             */
            mark: "stated" | "assumed" | "default";
            /** Updated At */
            updated_at?: string | null;
        };
        /** ProfileUpdateIn */
        ProfileUpdateIn: {
            /** Path */
            path: string;
            /** Value */
            value: unknown;
            /**
             * By
             * @enum {string}
             */
            by: "assistant" | "user";
        };
        /** Program */
        Program: {
            /** Id */
            id: string;
            /** University */
            university: string;
            /** Country */
            country: string;
            /** City */
            city: string;
            /** Direction */
            direction: string;
            /** Language */
            language: string;
            /** Duration Months */
            duration_months?: number | null;
            /** Tuition Per Year */
            tuition_per_year?: number | null;
            /** Living Per Year */
            living_per_year?: number | null;
            /** Currency */
            currency: string;
            /** Requirements */
            requirements: components["schemas"]["Requirement"][];
            /** Deadlines */
            deadlines: components["schemas"]["Deadline"][];
            /** Scholarships Note */
            scholarships_note?: string | null;
            /** Environment Text */
            environment_text?: string | null;
            /** Source Url */
            source_url: string;
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
            /** Is Demo */
            is_demo: boolean;
            /** Extracted Auto */
            extracted_auto: boolean;
            /** Flagged */
            flagged: boolean;
        };
        /** Questionnaire */
        Questionnaire: {
            level?: components["schemas"]["Level"];
            direction?: components["schemas"]["Direction"];
            academics?: components["schemas"]["Academics"];
            preferences?: components["schemas"]["Preferences"];
            constraints?: components["schemas"]["Constraints"];
            priorities?: components["schemas"]["Priorities"];
            pace?: components["schemas"]["Pace"];
        };
        /** Requirement */
        Requirement: {
            /**
             * Type
             * @enum {string}
             */
            type: "exam_score" | "language" | "gpa" | "document" | "other";
            /** Exam Id */
            exam_id?: ("SAT_MATH" | "ENT_MATH") | null;
            /** Threshold */
            threshold?: number | null;
            /**
             * Comparator
             * @enum {string}
             */
            comparator: ">=" | "<=" | "range" | "present";
            /** Description */
            description: string;
            /** Source */
            source?: string | null;
        };
        /**
         * RootCauseOut
         * @description One edge from evidence to a root skill — memory-architecture §6.
         */
        RootCauseOut: {
            /** From Skill Id */
            from_skill_id: string;
            /** Root Skill Id */
            root_skill_id: string;
            /** Confidence */
            confidence: number;
            /**
             * Source
             * @enum {string}
             */
            source: "diagnostic" | "observer" | "rule";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SavedProgramWithProgram */
        SavedProgramWithProgram: {
            /** Program Id */
            program_id: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
            program: components["schemas"]["Program"];
        };
        /** SetEditIn */
        SetEditIn: {
            /** Skill Ids */
            skill_ids: string[] | null;
            /** Deadline */
            deadline: string | null;
        };
        /** SetOut */
        SetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Area Ids */
            area_ids: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "upcoming" | "current" | "done";
            /**
             * Kind
             * @enum {string}
             */
            kind: "regular" | "review" | "consolidation";
            /** Position */
            position: number;
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /** Reason */
            reason: string;
            /** Topics */
            topics: components["schemas"]["TopicOut"][];
            progress: components["schemas"]["SetProgress"];
            /** Opened At */
            opened_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** SetProgress */
        SetProgress: {
            /** Topics Closed */
            topics_closed: number;
            /** Topics Total */
            topics_total: number;
            /** Tasks Answered */
            tasks_answered: number;
            /** Tasks Correct */
            tasks_correct: number;
        };
        /** SetSummaryOut */
        SetSummaryOut: {
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            /** Text */
            text: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SetSwitchIn */
        SetSwitchIn: {
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
        };
        /** SetsByExam */
        SetsByExam: {
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            forecast: components["schemas"]["ForecastOut"] | null;
            current: components["schemas"]["SetOut"] | null;
            /** Upcoming */
            upcoming: components["schemas"]["SetOut"][];
            /** Done */
            done: components["schemas"]["SetOut"][];
        };
        /** SkillStateView */
        SkillStateView: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /** Area Id */
            area_id: string;
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /** Weight */
            weight: number;
            /** P Target */
            p_target: number;
            /**
             * Level
             * @enum {string}
             */
            level: "low_data" | "weak" | "shaky" | "solid" | "closed";
            /** P Recall */
            p_recall: number;
            /** Confidence */
            confidence: number;
            /**
             * Trend
             * @enum {string}
             */
            trend: "up" | "flat" | "down";
            /** Due At */
            due_at: string | null;
            /** Is Root */
            is_root: boolean;
            /** N Evidence */
            n_evidence: number;
        };
        /** Source */
        Source: {
            /** Label */
            label: string;
            /** Url */
            url: string | null;
            /** Checked At */
            checked_at: string | null;
            /** Is Demo */
            is_demo: boolean;
        };
        /** StudentCtx */
        StudentCtx: {
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Email */
            email: string;
        };
        /** TaskInstanceOut */
        TaskInstanceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Template Id */
            template_id: string;
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /**
             * Type
             * @enum {string}
             */
            type: "mcq4" | "mcq5" | "multi_select" | "numeric";
            /** Skill Id */
            skill_id: string;
            /** Stem Rendered */
            stem_rendered: string;
            /** Options */
            options: components["schemas"]["OptionOut"][];
            /** Figure Url */
            figure_url: string | null;
            /** Time Reference Sec */
            time_reference_sec: number;
            /** Difficulty */
            difficulty: number;
            /** Tags */
            tags: string[];
            /**
             * Mode
             * @enum {string}
             */
            mode: "topic" | "mock_set" | "mock_topic" | "mock_misconception" | "diagnostic" | "chat";
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "template" | "manual";
        };
        /** TaskRequestIn */
        TaskRequestIn: {
            /** Skill Id */
            skill_id: string | null;
            /** Set Id */
            set_id: string | null;
            /**
             * Mode
             * @default topic
             * @enum {string}
             */
            mode: "topic" | "mock_set" | "mock_topic" | "mock_misconception" | "diagnostic" | "chat";
            /** With Trap */
            with_trap: string | null;
            /**
             * Exclude Seen
             * @default true
             */
            exclude_seen: boolean;
        };
        /** TaskSkipIn */
        TaskSkipIn: {
            /**
             * Instance Id
             * Format: uuid
             */
            instance_id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "skipped" | "timed_out";
            /** Time Spent Sec */
            time_spent_sec: number;
        };
        /** TestDate */
        TestDate: {
            /**
             * Exam Id
             * @enum {string}
             */
            exam_id: "SAT_MATH" | "ENT_MATH";
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Registration Deadline
             * Format: date
             */
            registration_deadline: string;
            /** Late Deadline */
            late_deadline?: string | null;
            /** Source */
            source: string;
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
            /** Is Demo */
            is_demo: boolean;
        };
        /** TopicOut */
        TopicOut: {
            /** Skill Id */
            skill_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "topic" | "check" | "review";
            /** Position */
            position: number;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed";
            /**
             * Level
             * @enum {string}
             */
            level: "low_data" | "weak" | "shaky" | "solid" | "closed";
            /** Is Root */
            is_root: boolean;
            /** Misconception Labels */
            misconception_labels: string[];
            /** Subtitle */
            subtitle: string | null;
        };
        /** Traits */
        Traits: {
            /** Verbatim */
            verbatim?: string[];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentCtx"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentCtx"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    update_profile_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_saved_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SavedProgramWithProgram_"];
                };
            };
        };
    };
    save_program_saved__program_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_saved_saved__program_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_programs_programs_get: {
        parameters: {
            query?: {
                country?: string | null;
                direction?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Program_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_programs__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_chat__kind__messages_get: {
        parameters: {
            query?: {
                limit?: number;
                set_id?: string | null;
                topic_skill_id?: string | null;
            };
            header?: never;
            path: {
                kind: "selection" | "prep";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_chat__kind__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "selection" | "prep";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_version_prep_knowledge_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeVersionOut"];
                };
            };
        };
    };
    issue_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInstanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_task_tasks__instance_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_task_tasks__instance_id__skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskSkipIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_solution_tasks__instance_id__solution_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sets_sets_get: {
        parameters: {
            query: {
                exam_id: "SAT_MATH" | "ENT_MATH";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetsByExam"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_set_sets_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSwitchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetsByExam"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_set_sets__set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_set_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEditIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_set_sets__set_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_topic_sets__set_id__topics__skill_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_topic_sets__set_id__topics__skill_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_knowledge_get: {
        parameters: {
            query: {
                exam_id: "SAT_MATH" | "ENT_MATH";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_knowledge_explain__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispute_knowledge_misconceptions__misconception_id__dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                misconception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MisconceptionStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matching_matching_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_matching_matching_compare_get: {
        parameters: {
            query: {
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    mark_milestone_overview_milestones__key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MilestoneMarkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilestoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_diagnostic_diagnostic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticStartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_diagnostic_diagnostic_active_get: {
        parameters: {
            query: {
                exam_id: "SAT_MATH" | "ENT_MATH";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_diagnostic_diagnostic__run_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_diagnostic_diagnostic__run_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_mock_mocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockStartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mock_mocks__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_mock_mocks__run_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_mock_mocks__run_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
