"""Quack — the feed, the pace variants and the activity calendar (§8.1).

Nothing here is generated by a model: every recommendation is a rule over
numbers the rest of the system already computed (product-logic §3.6), and
the four pace variants are re-runs of the phase-2 forecast.
"""

from __future__ import annotations

from datetime import date as _date
from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, model_validator

from app.schemas.common import ErrorClass, ExamId
from app.schemas.knowledge import ForecastOut

Urgency = Literal["urgent", "high", "normal", "low"]
RecStatus = Literal["pending", "shown", "accepted", "declined", "expired"]
RecKind = Literal[
    "pace_variant",
    "milestone_due",
    "conflict",
    "next_set",
    "set_change",
    "program_new_fit",
    "saved_realism_shift",
    "diagnostic_suggested",
    "activity_pause",
]
ActionKind = Literal[
    "profile_update",
    "requirement_update",
    "program_remove",
    "set_open",
    "set_edit",
    "milestone_open",
    "acknowledge",
]
PaceVariantKind = Literal["more_hours", "move_date", "remove_program", "lower_target"]

_URGENCY_ORDER: dict[str, int] = {"urgent": 0, "high": 1, "normal": 2, "low": 3}


def urgency_rank(urgency: str) -> int:
    """Feed order: urgent → high → normal → low."""
    return _URGENCY_ORDER.get(urgency, 9)


class RecommendationAction(BaseModel):
    """What accepting the recommendation does — §14.7 spells out per-kind
    requirements, and the validator below enforces them."""

    kind: ActionKind
    profile_path: str | None = None
    profile_value: Any | None = None
    exam_id: ExamId | None = None
    target_score: float | None = None
    test_date: _date | None = None
    program_id: str | None = None
    set_id: UUID | None = None
    skill_ids: list[str] | None = None
    deadline: _date | None = None
    milestone_key: str | None = None

    @model_validator(mode="after")
    def _required_by_kind(self) -> RecommendationAction:
        if self.kind == "profile_update" and (
            self.profile_path is None or self.profile_value is None
        ):
            raise ValueError("profile_update needs profile_path and profile_value")
        if self.kind == "requirement_update" and (
            self.exam_id is None
            or (self.target_score is None and self.test_date is None)
        ):
            raise ValueError("requirement_update needs exam_id and a target or a date")
        if self.kind == "program_remove" and self.program_id is None:
            raise ValueError("program_remove needs program_id")
        if self.kind == "set_open" and self.set_id is None:
            raise ValueError("set_open needs set_id")
        if self.kind == "set_edit" and (
            self.set_id is None or (self.skill_ids is None and self.deadline is None)
        ):
            raise ValueError("set_edit needs set_id and skill_ids or deadline")
        if self.kind == "milestone_open" and self.milestone_key is None:
            raise ValueError("milestone_open needs milestone_key")
        return self


class RecommendationOut(BaseModel):
    id: UUID
    kind: RecKind
    urgency: Urgency
    position: int
    status: RecStatus
    title: str
    reason: str
    action_text: str
    action: RecommendationAction
    forecast_after: ForecastOut | None = None
    exam_id: ExamId | None = None
    program_id: str | None = None
    milestone_key: str | None = None
    reason_hash: str
    created_at: AwareDatetime
    shown_at: AwareDatetime | None = None
    decided_at: AwareDatetime | None = None
    expires_at: AwareDatetime | None = None


class RecDraft(BaseModel):
    """What `quack.plan.plan` returns — a recommendation before it has an id."""

    kind: RecKind
    urgency: Urgency
    title: str
    reason: str
    action_text: str
    action: RecommendationAction
    reason_hash: str
    exam_id: ExamId | None = None
    program_id: str | None = None
    milestone_key: str | None = None
    forecast_after: ForecastOut | None = None
    expires_at: AwareDatetime | None = None
    position: int = 0


class PaceVariantOut(BaseModel):
    kind: PaceVariantKind
    text: str
    params: dict[str, Any] = Field(default_factory=dict)
    # Обязателен даже при `available=False` — тогда это базовый прогноз.
    forecast: ForecastOut
    available: bool
    unavailable_reason: str | None = None
    affected_program_ids: list[str] = Field(default_factory=list)
    recommendation_id: UUID | None = None


class ExamPaceOut(BaseModel):
    exam_id: ExamId
    forecast: ForecastOut | None = None
    on_track: bool | None = None
    test_date: _date | None = None
    hours_declared: int | None = None
    hours_actual: float | None = None
    variants: list[PaceVariantOut] = Field(default_factory=list)
    words: str = ""


class PaceOut(BaseModel):
    exams: list[ExamPaceOut] = Field(default_factory=list)
    as_of: AwareDatetime


class ActivityDay(BaseModel):
    day: _date
    active: bool
    tasks_answered: int = 0
    mocks_completed: int = 0
    chat_messages: int = 0
    active_minutes: int = 0


class ActivityOut(BaseModel):
    days: list[ActivityDay] = Field(default_factory=list)
    window_days: int
    active_days: int
    hours_per_week_actual: float | None = None
    hours_per_week_declared: int | None = None
    computed_at: AwareDatetime | None = None
    tz: str


class QuackOut(BaseModel):
    pace: PaceOut
    items: list[RecommendationOut] = Field(default_factory=list)
    activity: ActivityOut
    new_batch: bool = False
    batch_at: AwareDatetime | None = None
    n_new: int = 0


class QuackSeenIn(BaseModel):
    recommendation_ids: list[UUID] | None = None


class RecDecisionIn(BaseModel):
    reason: str | None = None


# --- aggregates (§9.1) ---


class PaceSignals(BaseModel):
    timeouts_7d: int = 0
    asked_to_slow_down_7d: int = 0
    hurried_share_7d: float | None = None
    late_session_share_7d: float | None = None


class DailyAggregatePayload(BaseModel):
    day: _date
    tz: str
    sessions: int = 0
    active_minutes: int = 0
    tasks_answered: int = 0
    tasks_correct: int = 0
    tasks_timed_out: int = 0
    mocks_completed: int = 0
    chat_messages: int = 0
    guidelines_opened: int = 0
    first_event_at: datetime | None = None
    last_event_at: datetime | None = None


class StudentAggregates(BaseModel):
    student_id: UUID
    window_days: int
    computed_at: AwareDatetime
    as_of_event_id: int = 0
    # Σ active_minutes за последние 7 полных дней / 60.
    hours_per_week_actual: float = 0.0
    hours_per_week_declared: int | None = None
    active_days: int = 0
    active_days_by_day: dict[str, bool] = Field(default_factory=dict)
    # Доли по Σ occurrence_count заблуждений; Σ = 1 или {} при отсутствии.
    error_class_dist: dict[ErrorClass, float] = Field(default_factory=dict)
    pace_signals: PaceSignals = Field(default_factory=PaceSignals)
    graph_stale: bool = False


class BatchResult(BaseModel):
    created: int = 0
    updated: int = 0
    expired: int = 0
    batch_id: UUID | None = None


__all__ = [
    "ActionKind",
    "ActivityDay",
    "ActivityOut",
    "BatchResult",
    "DailyAggregatePayload",
    "ExamPaceOut",
    "PaceOut",
    "PaceSignals",
    "PaceVariantKind",
    "PaceVariantOut",
    "QuackOut",
    "QuackSeenIn",
    "RecDecisionIn",
    "RecDraft",
    "RecKind",
    "RecStatus",
    "RecommendationAction",
    "RecommendationOut",
    "StudentAggregates",
    "Urgency",
    "urgency_rank",
]
